"use client";

import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import {
  Sparkles,
  MapPin,
  Share2,
  Star,
  CheckCircle2,
  TrendingUp,
  ArrowRight,
  ShieldCheck,
  Zap,
  Calendar,
  MessageCircle,
  BarChart3,
  Bot,
  Store,
  Utensils,
  Scissors,
  Stethoscope,
  Dumbbell,
  Smartphone,
  Eye,
  ChevronLeft,
  ChevronRight,
  Layers,
  Award,
} from "lucide-react";
import { AppleLogo, GooglePlayLogo } from "@/components/ui/BrandIcons";
import { Button } from "@/components/ui/button";
import { BRAND_NAME, WHATSAPP_LINK, APP_STORE_URL, PLAY_STORE_URL } from "@/lib/constants";
import { LeadForm } from "@/components/shared/LeadForm";
import { ThreeDCard } from "@/components/ui/ThreeDCard";
import { CoreGrowthEngines } from "@/components/home/CoreGrowthEngines";
import { ProblemsWeSolve } from "@/components/home/ProblemsWeSolve";
import { FramerHero } from "@/components/home/FramerHero";
import { ApplioFeatures } from "@/components/home/ApplioFeatures";
import { RevealOnScroll, ParallaxItem } from "@/components/ui/ParallaxSection";

const appScreenshots = [
  {
    badge: "Auto Review Replies",
    title: "AI-Powered Auto Replies on Reviews",
    desc: "Every Google review receives an instant, contextual, and polite reply generated by AI. Never leave customers waiting while you manage your busy shop.",
    metric: "16 Pending Reviews Cleared in Seconds",
    url: "/images/app-screen-0.png",
  },
  {
    badge: "Google Audit Score",
    title: "Detailed Google Business Report Analysis",
    desc: "Instant health audit analyzing your Google Maps listing completeness, verification status, active posting days, and missed ranking factors.",
    metric: "0–100 Actionable Profile Health Score",
    url: "/images/app-screen-1.png",
  },
  {
    badge: "Competitor Intelligence",
    title: "Know Your Competitors & Market Share",
    desc: "Deep-dive into nearby competitor ratings, total review counts, and operational strengths & weaknesses to outrank them in local 3-pack searches.",
    metric: "Real-time Competitor Benchmarking",
    url: "/images/app-screen-2.png",
  },
  {
    badge: "Keyword Ranking",
    title: "Rank Higher with Top Local Keywords",
    desc: "Identify the exact search keywords nearby customers type into Google (e.g. 'best restaurant near me', 'open now') and optimize your profile.",
    metric: "Top Search Keyword Radar Across Your Pin Radius",
    url: "/images/app-screen-3.png",
  },
  {
    badge: "WhatsApp Integration",
    title: "Daily Performance Reports on WhatsApp",
    desc: "Get morning business summaries, review alerts, and 1-tap AI approval prompts sent directly to your WhatsApp without opening complex software.",
    metric: "Zero Dashboard Fatigue • 100% WhatsApp Native",
    url: "/images/app-screen-4.png",
  },
];

const industries = {
  restaurants: {
    tabLabel: "Restaurants & Cafes",
    title: "Restaurants, Cafes & Bakeries",
    icon: Utensils,
    mapsKeyword: "Best Biryani & Chinese near me",
    rankChange: "#8 → #1 on Google Maps",
    postIdea: "Weekend Special: Buy 1 Chef's Special Pizza & Get Garlic Bread Free! 🍕",
    reviewMsg: "Thank you for dining at Spice Hub! Please rate your experience on Google ⭐",
    benefit: "Fill tables on slow weekdays with automated festival and weekend promo posts.",
  },
  retail: {
    tabLabel: "Retail & Stores",
    title: "Clothing, Electronics & Retail Stores",
    icon: Store,
    mapsKeyword: "Designer Kurti & Sarees near me",
    rankChange: "#14 → #2 on Google Maps",
    postIdea: "Festive Clearance Sale: Flat 40% OFF on all new arrivals this weekend only! ✨",
    reviewMsg: "Thank you for shopping at Royal Fashion! Tap here to share a 5★ review on Google.",
    benefit: "Drives foot traffic into your physical storefront instead of losing buyers online.",
  },
  salons: {
    tabLabel: "Salons & Spas",
    title: "Salons, Parlours & Spas",
    icon: Scissors,
    mapsKeyword: "Best Bridal Makeup & Hair Spa near me",
    rankChange: "#11 → #1 on Google Maps",
    postIdea: "Pre-Wedding Glow Package: HydraFacial + Hair Botox at flat ₹1,999! 💇‍♀️",
    reviewMsg: "Loved your makeover at Glamour Studio? Rate us on Google and get 10% off next visit!",
    benefit: "Keeps appointment books full with seasonal makeover banners and viral reels ideas.",
  },
  clinics: {
    tabLabel: "Clinics & Doctors",
    title: "Dental, Clinics & Health Centers",
    icon: Stethoscope,
    mapsKeyword: "Dentist & Dental Implant Clinic near me",
    rankChange: "#9 → #1 on Google Maps",
    postIdea: "Painless Dental Consultation & Scaling Week: Prioritize your oral health today! 🦷",
    reviewMsg: "We care for your health! Please share your experience with Dr. Sharma on Google.",
    benefit: "Builds unshakeable patient trust with authenticated 5-star Google ratings.",
  },
  gyms: {
    tabLabel: "Gyms & Fitness",
    title: "Gyms, Crossfit & Fitness Studios",
    icon: Dumbbell,
    mapsKeyword: "Best Unisex Gym & Personal Trainer near me",
    rankChange: "#12 → #2 on Google Maps",
    postIdea: "Transform in 90 Days: New Year Fitness Batch opening with 30% early bird discount! 💪",
    reviewMsg: "Crushed your workout at Iron Fitness? Drop us a 5-star review on Google!",
    benefit: "Converts seasonal inquiries into year-long memberships with targeted social creatives.",
  },
};

export default function HomePage() {
  const [activeTab, setActiveTab] = useState<keyof typeof industries>("restaurants");
  const [activeScreenIndex, setActiveScreenIndex] = useState(0);

  const nextScreen = () => {
    setActiveScreenIndex((prev) => (prev + 1) % appScreenshots.length);
  };

  const prevScreen = () => {
    setActiveScreenIndex((prev) => (prev - 1 + appScreenshots.length) % appScreenshots.length);
  };

  return (
    <div className="bg-[#050508] text-zinc-100 min-h-screen relative overflow-hidden font-sans">
      {/* Framer-grade Ambient Glows */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[500px] bg-purple-600/10 rounded-full blur-[150px] pointer-events-none" />
      <div className="absolute top-[1400px] -left-48 w-[600px] h-[600px] bg-cyan-600/8 rounded-full blur-[160px] pointer-events-none" />
      <div className="absolute top-[2800px] -right-48 w-[600px] h-[600px] bg-purple-600/8 rounded-full blur-[160px] pointer-events-none" />

      {/* ──────────────────────────────────────────
          HERO SECTION: Framer Style Software Showcase
      ────────────────────────────────────────── */}
      <FramerHero />

      {/* ──────────────────────────────────────────
          STATS BAR: PROOF COUNTERS
      ────────────────────────────────────────── */}
      <RevealOnScroll direction="up" delay={0.1}>
        <section className="border-y border-white/10 bg-[#07071a]/90 py-10 px-4 relative z-20">
          <div className="container mx-auto max-w-7xl">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
              <div className="space-y-1">
                <div className="text-3xl md:text-5xl font-black text-gradient-brand">
                  10,000+
                </div>
                <div className="text-xs md:text-sm text-slate-400 font-medium">Local Businesses Active</div>
              </div>
              <div className="space-y-1">
                <div className="text-3xl md:text-5xl font-black text-gradient-brand">
                  50,000+
                </div>
                <div className="text-xs md:text-sm text-slate-400 font-medium">5-Star Reviews Gathered</div>
              </div>
              <div className="space-y-1">
                <div className="text-3xl md:text-5xl font-black text-gradient-brand">
                  2,000,000+
                </div>
                <div className="text-xs md:text-sm text-slate-400 font-medium">AI Creatives & Posts</div>
              </div>
              <div className="space-y-1">
                <div className="text-3xl md:text-5xl font-black text-gradient-brand">
                  4.8 / 5.0
                </div>
                <div className="text-xs md:text-sm text-slate-400 font-medium">Merchant Satisfaction Rating</div>
              </div>
            </div>
          </div>
        </section>
      </RevealOnScroll>

      {/* ──────────────────────────────────────────
          PROBLEMS WE SOLVE: 4 COSTLY VISIBILITY PROBLEMS
      ────────────────────────────────────────── */}
      <ProblemsWeSolve />

      {/* ──────────────────────────────────────────
          CORE ENGINES: GOOGLE RANKING & SOCIAL AUTOMATION
      ────────────────────────────────────────── */}
      <CoreGrowthEngines />

      {/* ──────────────────────────────────────────
          3D FEATURE 1: GOOGLE MAPS DOMINANCE
      ────────────────────────────────────────── */}
      <section className="py-24 px-4 container mx-auto max-w-7xl relative overflow-hidden">
        <div className="grid lg:grid-cols-12 gap-12 items-center">
          {/* Left Text */}
          <div className="lg:col-span-6">
            <RevealOnScroll direction="left" delay={0.1}>
              <div className="space-y-6">
                <span className="text-xs font-bold text-purple-400 uppercase tracking-widest bg-purple-500/10 px-3.5 py-1.5 rounded-full border border-purple-500/20">
                  Feature 01 • Local SEO Radar
                </span>
                <h2 className="font-heading text-3xl md:text-5xl font-extrabold text-white tracking-tight leading-tight">
                  Skyrocket Your <br />
                  <span className="text-gradient-brand">
                    Google Maps Ranking
                  </span>
                </h2>
                <p className="text-base md:text-lg text-slate-300 leading-relaxed">
                  When nearby customers search for what you sell, 70% of calls and store visits go to the top 3 spots on Google Maps. Dhanda Grow audits your profile, detects high-converting local search terms, and systematically propels your business to #1.
                </p>

                <div className="grid sm:grid-cols-2 gap-4 pt-2">
                  <div className="glass-card p-4 rounded-2xl border border-white/10">
                    <div className="w-8 h-8 rounded-lg bg-purple-500/20 flex items-center justify-center text-purple-400 mb-2">
                      <BarChart3 className="w-4 h-4" />
                    </div>
                    <h3 className="font-bold text-white text-sm">Health Score Radar</h3>
                    <p className="text-xs text-slate-400 mt-1">Audit 30+ ranking factors on your profile.</p>
                  </div>

                  <div className="glass-card p-4 rounded-2xl border border-white/10">
                    <div className="w-8 h-8 rounded-lg bg-cyan-500/20 flex items-center justify-center text-cyan-400 mb-2">
                      <Eye className="w-4 h-4" />
                    </div>
                    <h3 className="font-bold text-white text-sm">Competitor Radar</h3>
                    <p className="text-xs text-slate-400 mt-1">See competitor ranks across all neighborhood pins.</p>
                  </div>

                  <div className="glass-card p-4 rounded-2xl border border-white/10">
                    <div className="w-8 h-8 rounded-lg bg-emerald-500/20 flex items-center justify-center text-emerald-400 mb-2">
                      <MapPin className="w-4 h-4" />
                    </div>
                    <h3 className="font-bold text-white text-sm">Keyword Optimization</h3>
                    <p className="text-xs text-slate-400 mt-1">Target "near me" keywords that bring buyers.</p>
                  </div>

                  <div className="glass-card p-4 rounded-2xl border border-white/10">
                    <div className="w-8 h-8 rounded-lg bg-pink-500/20 flex items-center justify-center text-pink-400 mb-2">
                      <TrendingUp className="w-4 h-4" />
                    </div>
                    <h3 className="font-bold text-white text-sm">Traffic & Call Growth</h3>
                    <p className="text-xs text-slate-400 mt-1">Track direction taps and phone inquiries live.</p>
                  </div>
                </div>
              </div>
            </RevealOnScroll>
          </div>

          {/* Right 3D Visual with Floating Parallax Badge */}
          <div className="lg:col-span-6 relative">
            <RevealOnScroll direction="right" delay={0.15}>
              <div className="relative">
                <ParallaxItem speed={-0.12} className="hidden sm:block absolute -top-4 -right-4 z-20 pointer-events-none">
                  <div className="px-3.5 py-1.5 rounded-full bg-cyan-950/90 border border-cyan-400/40 text-cyan-200 text-xs font-semibold shadow-xl backdrop-blur-md flex items-center gap-1.5">
                    <MapPin className="w-3.5 h-3.5 text-cyan-400" />
                    <span>+340% Local Footfall</span>
                  </div>
                </ParallaxItem>

                <ThreeDCard depth={25} glowColor="rgba(6, 182, 212, 0.4)">
                  <div className="relative rounded-3xl overflow-hidden border border-white/20 shadow-2xl bg-[#0a0a24] p-3">
                    <div className="relative aspect-[4/3] w-full rounded-2xl overflow-hidden">
                      <Image
                        src="/images/3d-maps-radar.jpg"
                        alt="3D Google Maps Ranking Radar and Rating Shield"
                        fill
                        className="object-cover object-center"
                      />
                    </div>

                    <div className="p-4 mt-2 rounded-2xl bg-black/80 backdrop-blur-md border border-white/10">
                      <div className="flex items-center justify-between">
                        <div>
                          <div className="text-xs text-cyan-300 font-bold uppercase tracking-wider">Neighborhood Grid Telemetry</div>
                          <div className="text-sm font-black text-white">Dominating 12 of 14 Local Geocodes</div>
                        </div>
                        <span className="px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-300 text-xs font-bold">
                          Top 3 Active
                        </span>
                      </div>
                    </div>
                  </div>
                </ThreeDCard>
              </div>
            </RevealOnScroll>
          </div>
        </div>
      </section>

      {/* ──────────────────────────────────────────
          3D FEATURE 2: SOCIAL CREATIVE STUDIO
      ────────────────────────────────────────── */}
      <section className="py-24 px-4 container mx-auto max-w-7xl relative border-t border-white/10 overflow-hidden">
        <div className="grid lg:grid-cols-12 gap-12 items-center">
          {/* Left 3D Visual (Alternating) */}
          <div className="lg:col-span-6 order-2 lg:order-1 relative">
            <RevealOnScroll direction="left" delay={0.15}>
              <div className="relative">
                <ParallaxItem speed={0.12} className="hidden sm:block absolute -top-4 -left-4 z-20 pointer-events-none">
                  <div className="px-3.5 py-1.5 rounded-full bg-purple-950/90 border border-purple-400/40 text-purple-200 text-xs font-semibold shadow-xl backdrop-blur-md flex items-center gap-1.5">
                    <Sparkles className="w-3.5 h-3.5 text-pink-400" />
                    <span>365 Festival Posters Ready</span>
                  </div>
                </ParallaxItem>

                <ThreeDCard depth={25} glowColor="rgba(168, 85, 247, 0.45)">
                  <div className="relative rounded-3xl overflow-hidden border border-white/20 shadow-2xl bg-[#0c0c2a] p-3">
                    <div className="relative aspect-[4/3] w-full rounded-2xl overflow-hidden">
                      <Image
                        src="/images/3d-social-studio.jpg"
                        alt="3D AI Social Media Generator Studio with Floating Phone and Festival Posters"
                        fill
                        className="object-cover object-center"
                      />
                    </div>

                    <div className="p-4 mt-2 rounded-2xl bg-black/80 backdrop-blur-md border border-white/10">
                      <div className="flex items-center justify-between">
                        <div>
                          <div className="text-xs text-purple-300 font-bold uppercase tracking-wider">AI Content Studio</div>
                          <div className="text-sm font-black text-white">Diwali & Holiday Campaign Auto-Generated</div>
                        </div>
                        <span className="px-3 py-1 rounded-full bg-purple-500/20 text-purple-300 text-xs font-bold">
                          1-Tap Publish
                        </span>
                      </div>
                    </div>
                  </div>
                </ThreeDCard>
              </div>
            </RevealOnScroll>
          </div>

          {/* Right Text */}
          <div className="lg:col-span-6 order-1 lg:order-2">
            <RevealOnScroll direction="right" delay={0.1}>
              <div className="space-y-6">
                <span className="text-xs font-bold text-cyan-400 uppercase tracking-widest bg-cyan-500/10 px-3.5 py-1.5 rounded-full border border-cyan-500/20">
                  Feature 02 • Social Media Autopilot
                </span>
                <h2 className="font-heading text-3xl md:text-5xl font-extrabold text-white tracking-tight leading-tight">
                  Post Every Day Without <br />
                  <span className="text-gradient-brand">
                    Designing Anything
                  </span>
                </h2>
                <p className="text-base md:text-lg text-slate-300 leading-relaxed">
                  Never stare at a blank screen again. Dhanda Grow creates stunning festive posters, discount banners, and engaging Hindi/English captions customized with your logo, phone number, and shop address in 1-click.
                </p>

                <div className="grid sm:grid-cols-2 gap-4 pt-2">
                  <div className="glass-card p-4 rounded-2xl border border-white/10">
                    <div className="w-8 h-8 rounded-lg bg-cyan-500/20 flex items-center justify-center text-cyan-400 mb-2">
                      <Share2 className="w-4 h-4" />
                    </div>
                    <h3 className="font-bold text-white text-sm">1-Click Cross-Posting</h3>
                    <p className="text-xs text-slate-400 mt-1">Publish to Facebook, Instagram & WhatsApp Status at once.</p>
                  </div>

                  <div className="glass-card p-4 rounded-2xl border border-white/10">
                    <div className="w-8 h-8 rounded-lg bg-purple-500/20 flex items-center justify-center text-purple-400 mb-2">
                      <Calendar className="w-4 h-4" />
                    </div>
                    <h3 className="font-bold text-white text-sm">Indian Festival Calendar</h3>
                    <p className="text-xs text-slate-400 mt-1">Automatic banners for Diwali, Holi, Eid, and regional events.</p>
                  </div>

                  <div className="glass-card p-4 rounded-2xl border border-white/10">
                    <div className="w-8 h-8 rounded-lg bg-emerald-500/20 flex items-center justify-center text-emerald-400 mb-2">
                      <Bot className="w-4 h-4" />
                    </div>
                    <h3 className="font-bold text-white text-sm">Smart AI Captions</h3>
                    <p className="text-xs text-slate-400 mt-1">Viral local captions and hashtags generated automatically.</p>
                  </div>

                  <div className="glass-card p-4 rounded-2xl border border-white/10">
                    <div className="w-8 h-8 rounded-lg bg-amber-500/20 flex items-center justify-center text-amber-400 mb-2">
                      <ShieldCheck className="w-4 h-4" />
                    </div>
                    <h3 className="font-bold text-white text-sm">Automated Watermark</h3>
                    <p className="text-xs text-slate-400 mt-1">Your brand logo and contact details stamped on every graphic.</p>
                  </div>
                </div>
              </div>
            </RevealOnScroll>
          </div>
        </div>
      </section>

      {/* ──────────────────────────────────────────
          3D FEATURE 3: 5-STAR WHATSAPP REVIEW ENGINE
      ────────────────────────────────────────── */}
      <section className="py-24 px-4 container mx-auto max-w-7xl relative border-t border-white/10 overflow-hidden">
        <div className="grid lg:grid-cols-12 gap-12 items-center">
          <div className="lg:col-span-6">
            <RevealOnScroll direction="left" delay={0.1}>
              <div className="space-y-6">
                <span className="text-xs font-bold text-emerald-400 uppercase tracking-widest bg-emerald-500/10 px-3.5 py-1.5 rounded-full border border-emerald-500/20">
                  Feature 03 • 5★ Reputation Engine
                </span>
                <h2 className="font-heading text-3xl md:text-5xl font-extrabold text-white tracking-tight leading-tight">
                  Turn Happy Customers into <br />
                  <span className="text-gradient-brand">
                    5-Star Google Reviews
                  </span>
                </h2>
                <p className="text-base md:text-lg text-slate-300 leading-relaxed">
                  93% of shoppers read Google reviews before entering a local store. Dhanda Grow makes gathering reviews seamless by dispatching courteous 1-click WhatsApp review requests and replying to every review in seconds with AI.
                </p>

                <div className="grid sm:grid-cols-2 gap-4 pt-2">
                  <div className="glass-card p-4 rounded-2xl border border-white/10">
                    <div className="w-8 h-8 rounded-lg bg-emerald-500/20 flex items-center justify-center text-emerald-400 mb-2">
                      <MessageCircle className="w-4 h-4" />
                    </div>
                    <h3 className="font-bold text-white text-sm">WhatsApp Direct Prompts</h3>
                    <p className="text-xs text-slate-400 mt-1">Send 1-tap review links directly to happy customers.</p>
                  </div>

                  <div className="glass-card p-4 rounded-2xl border border-white/10">
                    <div className="w-8 h-8 rounded-lg bg-purple-500/20 flex items-center justify-center text-purple-400 mb-2">
                      <Bot className="w-4 h-4" />
                    </div>
                    <h3 className="font-bold text-white text-sm">Instant 4-Second Replies</h3>
                    <p className="text-xs text-slate-400 mt-1">AI replies with personalized gratitude 24/7.</p>
                  </div>

                  <div className="glass-card p-4 rounded-2xl border border-white/10">
                    <div className="w-8 h-8 rounded-lg bg-amber-500/20 flex items-center justify-center text-amber-400 mb-2">
                      <ShieldCheck className="w-4 h-4" />
                    </div>
                    <h3 className="font-bold text-white text-sm">Negative Review Shield</h3>
                    <p className="text-xs text-slate-400 mt-1">Intercept complaints privately before they hit public ratings.</p>
                  </div>

                  <div className="glass-card p-4 rounded-2xl border border-white/10">
                    <div className="w-8 h-8 rounded-lg bg-cyan-500/20 flex items-center justify-center text-cyan-400 mb-2">
                      <TrendingUp className="w-4 h-4" />
                    </div>
                    <h3 className="font-bold text-white text-sm">Trust Velocity</h3>
                    <p className="text-xs text-slate-400 mt-1">Build unstoppable credibility in your town.</p>
                  </div>
                </div>
              </div>
            </RevealOnScroll>
          </div>

          {/* Right Interactive Card */}
          <div className="lg:col-span-6 relative">
            <RevealOnScroll direction="right" delay={0.15}>
              <div className="relative">
                <ParallaxItem speed={-0.12} className="hidden sm:block absolute -bottom-4 -right-4 z-20 pointer-events-none">
                  <div className="px-3.5 py-1.5 rounded-full bg-emerald-950/90 border border-emerald-400/40 text-emerald-200 text-xs font-semibold shadow-xl backdrop-blur-md flex items-center gap-1.5">
                    <Star className="w-3.5 h-3.5 fill-amber-400 text-amber-400" />
                    <span>4.9★ Average Rating Verified</span>
                  </div>
                </ParallaxItem>

                <ThreeDCard depth={25} glowColor="rgba(37, 211, 102, 0.35)">
                  <div className="glass-card p-8 rounded-3xl border border-white/20 bg-gradient-to-b from-[#091b16] to-[#040c0b] shadow-2xl space-y-5">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-bold text-emerald-400 uppercase tracking-wider">
                        Automated WhatsApp Review Sequence
                      </span>
                      <span className="text-xs px-2.5 py-1 rounded-full bg-emerald-500/20 text-emerald-300 font-bold">
                        100% Automated
                      </span>
                    </div>

                    <div className="rounded-2xl p-5 bg-[#075e54]/30 border border-[#25d366]/40 space-y-2">
                      <div className="text-xs text-emerald-300 font-bold flex items-center gap-2">
                        <MessageCircle className="w-4 h-4 text-[#25d366]" /> Sent via WhatsApp to Customer:
                      </div>
                      <p className="text-xs md:text-sm text-white leading-relaxed">
                        &quot;Hi Ritu! Thank you for visiting [Your Shop] today. We hope you loved your experience! Tap here to leave a 5-star review on Google: bit.ly/rate-us&quot;
                      </p>
                    </div>

                    <div className="rounded-2xl p-4 bg-white/5 border border-white/10 space-y-1.5">
                      <div className="flex items-center justify-between">
                        <span className="text-xs font-bold text-white">Ritu Verma reviewed on Google Maps</span>
                        <div className="flex items-center gap-0.5 text-amber-400">
                          {[...Array(5)].map((_, i) => (
                            <Star key={i} className="w-3.5 h-3.5 fill-amber-400 text-amber-400" />
                          ))}
                        </div>
                      </div>
                      <p className="text-xs text-slate-300 italic">
                        &quot;Wonderful collection and polite staff! Very happy with my purchase.&quot;
                      </p>
                    </div>

                    <div className="rounded-2xl p-4 bg-purple-950/40 border border-purple-500/40 space-y-1">
                      <div className="text-xs font-bold text-purple-300 flex items-center gap-1.5">
                        <Bot className="w-4 h-4" /> AI Auto-Replied (Sent in 4 seconds):
                      </div>
                      <p className="text-xs text-slate-200">
                        &quot;Thank you so much Ritu! It was our pleasure to serve you. We look forward to welcoming you back soon!&quot;
                      </p>
                    </div>
                  </div>
                </ThreeDCard>
              </div>
            </RevealOnScroll>
          </div>
        </div>
      </section>

      {/* ──────────────────────────────────────────
          APPLIO APP FEATURES & TESTIMONIALS
      ────────────────────────────────────────── */}
      <ApplioFeatures />

      {/* ──────────────────────────────────────────
          3D APP SCREENSHOTS & MOBILE EXPERIENCE
      ────────────────────────────────────────── */}
      <section className="py-24 px-4 container mx-auto max-w-7xl relative border-t border-white/10 bg-[#060618]/60 overflow-hidden">
        <RevealOnScroll direction="up" delay={0.1}>
          <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
            <span className="text-xs font-bold text-purple-400 uppercase tracking-widest bg-purple-500/10 px-3.5 py-1.5 rounded-full border border-purple-500/20">
              Native Mobile Experience
            </span>
            <h2 className="font-heading text-3xl md:text-5xl font-extrabold text-white tracking-tight">
              Built for Busy Business Owners
            </h2>
            <p className="text-base md:text-lg text-slate-300">
              A clean, intuitive mobile app designed for busy entrepreneurs who need real customer results, not complexity.
            </p>
          </div>
        </RevealOnScroll>

        {/* Carousel / Interactive Mobile Showcase */}
        <div className="max-w-6xl mx-auto grid lg:grid-cols-12 gap-8 lg:gap-12 items-center">
          {/* Active Screen Display in High-Fidelity Showcase Frame */}
          <div className="lg:col-span-6 flex flex-col items-center justify-center">
            <RevealOnScroll direction="left" delay={0.15}>
              <div className="w-full max-w-[480px] rounded-3xl p-3 sm:p-4 bg-gradient-to-b from-white/[0.09] via-white/[0.04] to-transparent border border-white/15 shadow-[0_25px_60px_rgba(0,0,0,0.85)] backdrop-blur-xl">
                {/* Showcase Top Bar */}
                <div className="flex items-center justify-between pb-3 px-1 border-b border-white/10 mb-3">
                  <div className="flex items-center gap-1.5">
                    <div className="w-2.5 h-2.5 rounded-full bg-red-500/70" />
                    <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/70" />
                    <div className="w-2.5 h-2.5 rounded-full bg-emerald-500/70" />
                  </div>
                  <div className="text-[11px] font-mono font-medium text-zinc-400 bg-white/5 px-3 py-0.5 rounded-full border border-white/10">
                    dhanda.app • {appScreenshots[activeScreenIndex].badge}
                  </div>
                  <div className="flex items-center gap-1.5 text-[10px] font-medium text-emerald-400">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                    Live Sync
                  </div>
                </div>

                {/* Exact 1:1 Aspect Canvas with Zero-Crop Containment */}
                <div className="relative w-full aspect-square rounded-2xl overflow-hidden bg-[#070716] border border-white/10 shadow-inner flex items-center justify-center p-2">
                  <Image
                    src={appScreenshots[activeScreenIndex].url}
                    alt={appScreenshots[activeScreenIndex].title}
                    fill
                    sizes="(max-width: 768px) 100vw, 480px"
                    className="object-contain transition-all duration-300 rounded-xl"
                    priority
                  />
                </div>

                {/* Quick Thumbnails Row */}
                <div className="grid grid-cols-5 gap-2 pt-3 mt-1">
                  {appScreenshots.map((item, idx) => (
                    <button
                      key={idx}
                      onClick={() => setActiveScreenIndex(idx)}
                      className={`relative aspect-square rounded-lg overflow-hidden border transition-all ${
                        activeScreenIndex === idx
                          ? "border-purple-400 ring-2 ring-purple-500/50 scale-105 shadow-md shadow-purple-600/30"
                          : "border-white/10 opacity-60 hover:opacity-100 hover:border-white/30"
                      }`}
                    >
                      <Image
                        src={item.url}
                        alt={item.title}
                        fill
                        className="object-cover"
                      />
                    </button>
                  ))}
                </div>
              </div>
            </RevealOnScroll>
          </div>

          {/* Navigation & Screen Details */}
          <div className="lg:col-span-6">
            <RevealOnScroll direction="right" delay={0.2}>
              <div className="space-y-6">
                <div className="space-y-3">
                  <div className="flex items-center gap-3">
                    <span className="text-xs font-bold text-cyan-400 uppercase tracking-wider bg-cyan-500/10 px-3 py-1 rounded-full border border-cyan-500/20">
                      Screen {activeScreenIndex + 1} of {appScreenshots.length}
                    </span>
                    <span className="text-xs font-medium text-zinc-400 bg-white/5 px-2.5 py-1 rounded-full border border-white/5">
                      {appScreenshots[activeScreenIndex].badge}
                    </span>
                  </div>
                  <h3 className="font-heading text-2xl sm:text-3xl font-bold text-white tracking-tight">
                    {appScreenshots[activeScreenIndex].title}
                  </h3>
                  <p className="text-slate-300 text-sm sm:text-base leading-relaxed">
                    {appScreenshots[activeScreenIndex].desc}
                  </p>
                  
                  {/* Highlight Metric Pill */}
                  <div className="inline-flex items-center gap-2 px-3.5 py-2 rounded-xl bg-purple-500/10 border border-purple-500/20 text-purple-300 text-xs sm:text-sm font-semibold">
                    <Sparkles className="w-4 h-4 text-purple-400 shrink-0" />
                    <span>{appScreenshots[activeScreenIndex].metric}</span>
                  </div>
                </div>

                {/* Selector list */}
                <div className="space-y-2 pt-1">
                  {appScreenshots.map((screen, idx) => (
                    <button
                      key={idx}
                      onClick={() => setActiveScreenIndex(idx)}
                      className={`w-full text-left p-3.5 rounded-xl text-xs sm:text-sm font-semibold transition-all flex items-center justify-between border ${
                        activeScreenIndex === idx
                          ? "bg-gradient-to-r from-purple-950/60 to-purple-900/40 border-purple-500/60 text-white shadow-lg shadow-purple-950/40"
                          : "bg-white/[0.03] hover:bg-white/[0.07] border-white/5 text-slate-400 hover:text-white"
                      }`}
                    >
                      <div className="flex items-center gap-3">
                        <span className={`w-6 h-6 rounded-lg text-xs flex items-center justify-center font-bold ${
                          activeScreenIndex === idx ? "bg-purple-500 text-white" : "bg-white/5 text-zinc-400"
                        }`}>
                          0{idx + 1}
                        </span>
                        <span>{screen.title}</span>
                      </div>
                      {activeScreenIndex === idx && <ChevronRight className="w-4 h-4 text-cyan-300 shrink-0" />}
                    </button>
                  ))}
                </div>

                {/* Carousel Arrow Controls */}
                <div className="flex items-center justify-between pt-2">
                  <div className="flex gap-2">
                    {appScreenshots.map((_, idx) => (
                      <button
                        key={idx}
                        onClick={() => setActiveScreenIndex(idx)}
                        className={`h-2 rounded-full transition-all ${
                          activeScreenIndex === idx ? "w-8 bg-purple-500" : "w-2 bg-white/20 hover:bg-white/40"
                        }`}
                        aria-label={`Jump to screenshot ${idx + 1}`}
                      />
                    ))}
                  </div>
                  <div className="flex gap-3">
                    <button
                      onClick={prevScreen}
                      aria-label="Previous screenshot"
                      className="w-10 h-10 rounded-full bg-white/5 hover:bg-white/10 border border-white/10 flex items-center justify-center text-white transition-colors"
                    >
                      <ChevronLeft className="w-5 h-5" />
                    </button>
                    <button
                      onClick={nextScreen}
                      aria-label="Next screenshot"
                      className="w-10 h-10 rounded-full bg-white/5 hover:bg-white/10 border border-white/10 flex items-center justify-center text-white transition-colors"
                    >
                      <ChevronRight className="w-5 h-5" />
                    </button>
                  </div>
                </div>
              </div>
            </RevealOnScroll>
          </div>
        </div>
      </section>

      {/* ──────────────────────────────────────────
          INTERACTIVE INDUSTRY SELECTOR
      ────────────────────────────────────────── */}
      <section className="py-24 px-4 container mx-auto max-w-7xl relative border-t border-white/10 overflow-hidden">
        <RevealOnScroll direction="up" delay={0.1}>
          <div className="text-center max-w-3xl mx-auto mb-14 space-y-4">
            <span className="text-xs font-bold text-cyan-400 uppercase tracking-widest bg-cyan-500/10 px-3.5 py-1.5 rounded-full border border-cyan-500/20">
              Tailored For You
            </span>
            <h2 className="font-heading text-3xl md:text-5xl font-extrabold tracking-tight">
              Built for Every Local Business Category
            </h2>
            <p className="text-base md:text-lg text-slate-300">
              Select your category to see how Dhanda Grow automates your growth from day one.
            </p>

            <div className="flex flex-wrap justify-center gap-2 pt-4">
              {(Object.keys(industries) as (keyof typeof industries)[]).map((key) => {
                const item = industries[key];
                const Icon = item.icon;
                const isActive = activeTab === key;
                return (
                  <button
                    key={key}
                    onClick={() => setActiveTab(key)}
                    className={`inline-flex items-center gap-2 px-4 py-2.5 rounded-full text-xs md:text-sm font-semibold transition-all ${
                      isActive
                        ? "bg-gradient-brand text-white shadow-lg shadow-purple-600/30 scale-105"
                        : "bg-white/5 text-slate-300 hover:bg-white/10 border border-white/10"
                    }`}
                  >
                    <Icon className="w-4 h-4" />
                    <span>{item.tabLabel}</span>
                  </button>
                );
              })}
            </div>
          </div>
        </RevealOnScroll>

        <RevealOnScroll direction="up" delay={0.15}>
          <ThreeDCard depth={15} glowColor="rgba(124, 58, 237, 0.35)">
            <div className="max-w-4xl mx-auto glass-card rounded-3xl p-6 md:p-10 border border-purple-500/30 bg-gradient-to-b from-[#0f0f35] to-[#08081c] shadow-2xl">
              <div className="grid md:grid-cols-2 gap-8 items-center">
                <div className="space-y-4">
                  <div className="inline-flex items-center gap-2 text-xs font-bold text-cyan-400 uppercase tracking-wider">
                    <Sparkles className="w-4 h-4" /> Custom Industry Workflow
                  </div>
                  <h3 className="font-heading text-2xl md:text-3xl font-bold text-white">
                    {industries[activeTab].title}
                  </h3>
                  <p className="text-slate-300 text-sm md:text-base leading-relaxed">
                    {industries[activeTab].benefit}
                  </p>

                  <div className="space-y-3 pt-2">
                    <div className="flex items-center gap-2 text-sm text-slate-200">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                      <span><strong>Rank Radar:</strong> {industries[activeTab].rankChange}</span>
                    </div>
                    <div className="flex items-center gap-2 text-sm text-slate-200">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                      <span><strong>Target Search:</strong> &quot;{industries[activeTab].mapsKeyword}&quot;</span>
                    </div>
                  </div>

                  <div className="pt-2">
                    <Button asChild className="bg-gradient-brand text-white rounded-full px-6 py-2">
                      <Link href="/contact" className="inline-flex items-center gap-2">
                        <span>Activate for My Business</span>
                        <ArrowRight className="w-4 h-4" />
                      </Link>
                    </Button>
                  </div>
                </div>

                <div className="space-y-3 p-5 rounded-2xl bg-black/40 border border-white/10">
                  <div className="text-xs font-bold text-slate-400 uppercase tracking-wider">
                    Automated Creative Post
                  </div>
                  <div className="p-4 rounded-xl bg-purple-950/40 border border-purple-500/30 text-white font-medium text-xs leading-relaxed">
                    &quot;{industries[activeTab].postIdea}&quot;
                  </div>
                  <div className="text-xs font-bold text-slate-400 uppercase tracking-wider pt-2">
                    WhatsApp Review Message
                  </div>
                  <div className="p-4 rounded-xl bg-emerald-950/30 border border-emerald-500/30 text-slate-200 text-xs leading-relaxed">
                    &quot;{industries[activeTab].reviewMsg}&quot;
                  </div>
                </div>
              </div>
            </div>
          </ThreeDCard>
        </RevealOnScroll>
      </section>

      {/* ──────────────────────────────────────────
          COMPARISON TABLE: WHY DHANDA GROW WINS
      ────────────────────────────────────────── */}
      <section className="py-24 px-4 container mx-auto max-w-6xl relative border-t border-white/10 overflow-hidden">
        <RevealOnScroll direction="up" delay={0.1}>
          <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
            <span className="text-xs font-bold text-cyan-400 uppercase tracking-widest bg-cyan-500/10 px-3.5 py-1.5 rounded-full border border-cyan-500/20">
              Unbeatable Value
            </span>
            <h2 className="font-heading text-3xl md:text-5xl font-extrabold tracking-tight">
              Why Local Businesses Choose Dhanda Grow
            </h2>
            <p className="text-base md:text-lg text-slate-300">
              Compare Dhanda Grow against costly marketing agencies and stressful DIY attempts.
            </p>
          </div>
        </RevealOnScroll>

        <RevealOnScroll direction="up" delay={0.15}>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse glass-card rounded-3xl overflow-hidden border border-white/15">
              <thead>
                <tr className="border-b border-white/10 bg-white/5 text-xs md:text-sm">
                  <th className="p-5 text-slate-300 font-semibold">Features & Benefits</th>
                  <th className="p-5 text-slate-400 font-normal">Marketing Agency</th>
                  <th className="p-5 text-slate-400 font-normal">Doing It Yourself</th>
                  <th className="p-5 text-white font-bold bg-purple-900/40 border-l border-r border-purple-500/30">
                    <div className="flex items-center gap-1.5 text-cyan-300">
                      <Sparkles className="w-4 h-4" /> Dhanda Grow
                    </div>
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/10 text-xs md:text-sm">
                <tr>
                  <td className="p-5 font-semibold text-white">Monthly Cost</td>
                  <td className="p-5 text-slate-400">₹20,000 - ₹50,000 / mo</td>
                  <td className="p-5 text-slate-400">15+ hours of your free time</td>
                  <td className="p-5 font-bold text-emerald-400 bg-purple-900/20 border-l border-r border-purple-500/20">
                    Free / Affordable
                  </td>
                </tr>
                <tr>
                  <td className="p-5 font-semibold text-white">Google Maps Audit & Rank Tracking</td>
                  <td className="p-5 text-slate-400">Manual monthly report</td>
                  <td className="p-5 text-slate-400">Rarely done / Guesswork</td>
                  <td className="p-5 font-bold text-white bg-purple-900/20 border-l border-r border-purple-500/20">
                    Real-time 24/7 AI Radar
                  </td>
                </tr>
                <tr>
                  <td className="p-5 font-semibold text-white">Daily Social Posters & Festival Graphics</td>
                  <td className="p-5 text-slate-400">Takes 3-5 days per creative</td>
                  <td className="p-5 text-slate-400">Hours spent struggling with design</td>
                  <td className="p-5 font-bold text-white bg-purple-900/20 border-l border-r border-purple-500/20">
                    Instant 1-Click Generation
                  </td>
                </tr>
                <tr>
                  <td className="p-5 font-semibold text-white">WhatsApp Review Automation</td>
                  <td className="p-5 text-slate-400">Not included / Extra charge</td>
                  <td className="p-5 text-slate-400">Awkward to ask manually</td>
                  <td className="p-5 font-bold text-white bg-purple-900/20 border-l border-r border-purple-500/20">
                    100% Automated Workflow
                  </td>
                </tr>
                <tr>
                  <td className="p-5 font-semibold text-white">AI 24/7 Review Replies</td>
                  <td className="p-5 text-slate-400">Delayed by days</td>
                  <td className="p-5 text-slate-400">Ignored or forgotten</td>
                  <td className="p-5 font-bold text-white bg-purple-900/20 border-l border-r border-purple-500/20">
                    Instant under 10 seconds
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </RevealOnScroll>
      </section>

      {/* ──────────────────────────────────────────
          LEAD CAPTURE / STRATEGY DEMO SECTION
      ────────────────────────────────────────── */}
      <section className="py-24 px-4 container mx-auto max-w-5xl relative border-t border-white/10 overflow-hidden" id="lead-capture">
        <RevealOnScroll direction="up" delay={0.1}>
          <div className="grid md:grid-cols-12 gap-10 items-center">
            <div className="md:col-span-6 space-y-6">
              <span className="text-xs font-bold text-purple-400 uppercase tracking-widest bg-purple-500/10 px-3.5 py-1.5 rounded-full border border-purple-500/20">
                Get Started In 2 Minutes
              </span>
              <h2 className="font-heading text-3xl md:text-5xl font-extrabold tracking-tight">
                Get Your Free <span className="text-gradient-brand">Google Maps Audit</span> & Demo
              </h2>
              <p className="text-slate-300 text-base leading-relaxed">
                Drop your details below. Our growth specialist will run a complimentary audit of your Google Maps presence and demonstrate how Dhanda Grow will automate your marketing.
              </p>

              <ul className="space-y-3 text-sm text-slate-300">
                <li className="flex items-center gap-2.5">
                  <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                  <span>Complimentary Google Maps Competitor Analysis</span>
                </li>
                <li className="flex items-center gap-2.5">
                  <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                  <span>3 Free Festival Creatives tailored with your logo</span>
                </li>
                <li className="flex items-center gap-2.5">
                  <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                  <span>Zero obligations • 100% free consultation</span>
                </li>
              </ul>
            </div>

            <div className="md:col-span-6">
              <div className="glass-card rounded-3xl p-6 md:p-8 border border-purple-500/30 shadow-2xl bg-[#0a0a22]">
                <LeadForm />
              </div>
            </div>
          </div>
        </RevealOnScroll>
      </section>

      {/* ──────────────────────────────────────────
          FINAL DOWNLOAD CTA
      ────────────────────────────────────────── */}
      <section className="py-24 px-4 container mx-auto max-w-4xl text-center relative border-t border-white/10 overflow-hidden">
        <RevealOnScroll direction="up" delay={0.1}>
          <div className="space-y-6">
            <span className="text-xs font-bold text-cyan-400 uppercase tracking-widest bg-cyan-500/10 px-3.5 py-1.5 rounded-full border border-cyan-500/20">
              Start Today
            </span>
            <h2 className="font-heading text-3xl md:text-5xl font-extrabold text-white">
              Your Customers Are Searching on Google Maps Right Now. <br />
              <span className="text-gradient-brand">
                Will They Find You?
              </span>
            </h2>
            <p className="text-base md:text-lg text-slate-300 max-w-2xl mx-auto leading-relaxed">
              Join thousands of smart shop owners, restaurants, and doctors who dominate their local market with Dhanda Grow.
            </p>

            <div className="flex flex-col sm:flex-row justify-center items-center gap-4 pt-4">
              <Button
                size="lg"
                asChild
                className="w-full sm:w-auto h-14 px-8 rounded-full bg-gradient-brand hover:opacity-90 text-white font-bold text-lg shadow-2xl shadow-purple-600/40 hover:scale-105 transition-all"
              >
                <Link href="/contact" className="inline-flex items-center gap-2">
                  <Sparkles className="w-5 h-5" />
                  <span>Start Growing My Business</span>
                </Link>
              </Button>

              <Button
                size="lg"
                variant="outline"
                asChild
                className="w-full sm:w-auto h-14 px-8 rounded-full border-white/15 bg-white/5 hover:bg-white/10 text-white font-semibold text-lg hover:border-purple-400 transition-all"
              >
                <a href={WHATSAPP_LINK} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2">
                  <MessageCircle className="w-5 h-5 text-emerald-400" />
                  <span>Instant WhatsApp Help</span>
                </a>
              </Button>
            </div>

            <div className="flex flex-wrap justify-center items-center gap-4 pt-6">
              <a
                href={APP_STORE_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="px-5 py-2.5 rounded-2xl bg-white/5 hover:bg-white/10 border border-white/15 text-slate-200 text-xs font-bold transition-all hover:scale-105 inline-flex items-center gap-2"
              >
                <AppleLogo className="w-4 h-4 text-white" />
                <span>Download on App Store</span>
              </a>
              <a
                href={PLAY_STORE_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="px-5 py-2.5 rounded-2xl bg-white/5 hover:bg-white/10 border border-white/15 text-slate-200 text-xs font-bold transition-all hover:scale-105 inline-flex items-center gap-2"
              >
                <GooglePlayLogo className="w-4 h-4" />
                <span>Get it on Google Play</span>
              </a>
            </div>
          </div>
        </RevealOnScroll>
      </section>
    </div>
  );
}
