"use client";

import React, { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import {
  Sparkles,
  MapPin,
  Share2,
  Star,
  CheckCircle2,
  ArrowRight,
  TrendingUp,
  ShieldCheck,
  Zap,
  Smartphone,
  MessageCircle,
  Wifi,
  Battery,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { BorderBeam } from "@/components/ui/BorderBeam";
import { ThreeDCard } from "@/components/ui/ThreeDCard";
import { APP_STORE_URL, PLAY_STORE_URL, WHATSAPP_LINK } from "@/lib/constants";

const appScreens = [
  {
    id: "dashboard",
    label: "AI Command",
    title: "Unified Growth Analytics",
    subtitle: "Track walk-ins, calls & direction clicks",
    image: "/images/dhanda-3d-hero.jpg",
    alt: "Dhanda Grow 3D AI Marketing Engine Dashboard",
    badgeColor: "bg-violet-500/20 text-violet-300 border-violet-500/30",
  },
  {
    id: "radar",
    label: "Maps Radar",
    title: "Google Maps Rank Radar",
    subtitle: "Real-time #1 Local 3-Pack tracking",
    image: "/images/3d-maps-radar.jpg",
    alt: "3D Google Maps Ranking Radar and Rating Shield",
    badgeColor: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
  },
  {
    id: "festival",
    label: "Festival Studio",
    title: "Daily Festival Creatives",
    subtitle: "Diwali, Holi & offers ready in 1-tap",
    image: "/images/3d-social-studio.jpg",
    alt: "3D AI Social Media Generator Studio with Floating Phone and Festival Posters",
    badgeColor: "bg-pink-500/20 text-pink-300 border-pink-500/30",
  },
  {
    id: "reviews",
    label: "Review Booster",
    title: "WhatsApp 5-Star Engine",
    subtitle: "Auto-invite happy customers to rate",
    image: "https://ezobooks.in/kfi/file/399735/evEcorR",
    alt: "WhatsApp 5-Star Review Automation Screen",
    badgeColor: "bg-amber-500/20 text-amber-300 border-amber-500/30",
  },
];

export function ApplioHero() {
  const [activeScreen, setActiveScreen] = useState(0);
  const current = appScreens[activeScreen];

  return (
    <section className="relative pt-8 pb-20 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto overflow-hidden">
      {/* Background Glows (NexApp / Applio Aesthetic) */}
      <div className="absolute top-10 left-1/2 -translate-x-1/2 w-[750px] h-[450px] bg-gradient-to-b from-violet-600/20 via-cyan-500/15 to-transparent blur-[140px] pointer-events-none rounded-full" />
      <div className="absolute top-1/2 -left-40 w-96 h-96 bg-purple-600/10 blur-[130px] pointer-events-none rounded-full" />
      <div className="absolute top-1/2 -right-40 w-96 h-96 bg-cyan-600/10 blur-[130px] pointer-events-none rounded-full" />

      {/* Header Info */}
      <div className="text-center max-w-4xl mx-auto relative z-10 mb-10">
        {/* App Announcement Badge */}
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold shimmer-pill text-zinc-300 mb-6 cursor-pointer hover:scale-105 transition-transform duration-200">
          <span className="flex h-2 w-2 rounded-full bg-cyan-400 animate-pulse" />
          <span className="text-white font-medium">Dhanda Grow App 2.0</span>
          <span className="text-zinc-500">•</span>
          <span className="text-cyan-300 flex items-center gap-1 font-semibold">
            Now Live on iOS & Android <ArrowRight className="w-3 h-3" />
          </span>
        </div>

        {/* Hero Title (Generated by MCP SEO Content Tool) */}
        <h1 className="text-4xl sm:text-6xl lg:text-7xl font-black tracking-tight text-white mb-6 leading-[1.08]">
          The Local Business Marketing App{" "}
          <span className="text-gradient">That Works While You Run Your Shop.</span>
        </h1>

        {/* Subtitle */}
        <p className="text-base sm:text-xl text-zinc-300 max-w-3xl mx-auto mb-8 leading-relaxed">
          Meet Dhanda Grow: the mobile-first AI marketing operating system built for India&apos;s shop owners, retailers, doctors, salons, cafes, and gym managers. Automate your Google Maps ranking, daily festival social posters, and 5-star WhatsApp reviews right from your phone.
        </p>

        {/* App Store & Google Play Download Button Cluster */}
        <div className="flex flex-wrap items-center justify-center gap-3.5 mb-8">
          {/* iOS App Store Badge */}
          <a
            href={APP_STORE_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-3 px-5 py-3 rounded-2xl bg-[#0c0c16] hover:bg-[#141424] border border-white/15 text-white shadow-xl hover:border-violet-500/40 transition-all hover:scale-105 group"
          >
            <span className="text-2xl leading-none"></span>
            <div className="text-left">
              <div className="text-[10px] text-zinc-400 uppercase font-mono tracking-wider leading-none">Download on the</div>
              <div className="text-sm font-bold text-white group-hover:text-violet-300 transition-colors">App Store</div>
            </div>
          </a>

          {/* Google Play Store Badge */}
          <a
            href={PLAY_STORE_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-3 px-5 py-3 rounded-2xl bg-[#0c0c16] hover:bg-[#141424] border border-white/15 text-white shadow-xl hover:border-cyan-500/40 transition-all hover:scale-105 group"
          >
            <span className="text-xl leading-none text-cyan-400">▶</span>
            <div className="text-left">
              <div className="text-[10px] text-zinc-400 uppercase font-mono tracking-wider leading-none">Get it on</div>
              <div className="text-sm font-bold text-white group-hover:text-cyan-300 transition-colors">Google Play</div>
            </div>
          </a>

          {/* Instant Strategy Demo CTA */}
          <Button
            asChild
            size="lg"
            className="h-13 px-6 rounded-2xl bg-gradient-to-r from-violet-600 to-cyan-600 hover:from-violet-500 hover:to-cyan-500 text-white font-bold text-sm shadow-lg shadow-violet-600/30 hover:scale-105 transition-all"
          >
            <a href="#lead-capture" className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-cyan-200" />
              <span>Free Setup Consultation</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </a>
          </Button>
        </div>

        {/* Rating and Social Proof Badges */}
        <div className="flex flex-wrap items-center justify-center gap-4 text-xs text-zinc-400">
          <div className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-white/5 border border-white/10">
            <div className="flex items-center text-amber-400">
              {[...Array(5)].map((_, i) => (
                <Star key={i} className="w-3.5 h-3.5 fill-amber-400" />
              ))}
            </div>
            <span className="font-bold text-white">4.9 / 5.0</span>
            <span className="text-zinc-500">•</span>
            <span>App Store & Play Store</span>
          </div>

          <span className="flex items-center gap-1.5 text-zinc-300">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" /> 10,000+ Active Shop Owners
          </span>
          <span className="flex items-center gap-1.5 text-zinc-300">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" /> Zero GST Forms or Paperwork
          </span>
        </div>
      </div>

      {/* ============================================================== */}
      {/* 3D FLOATING IPHONE SHOWCASE WITH ORBITING BADGES (APPLIO STYLE) */}
      {/* ============================================================== */}
      <div className="relative max-w-5xl mx-auto mt-6">
        {/* Interactive Screen Switcher Pills */}
        <div className="flex items-center justify-center gap-2 mb-8 flex-wrap">
          <div className="inline-flex p-1.5 rounded-2xl bg-zinc-950/90 border border-white/10 backdrop-blur-xl shadow-2xl">
            {appScreens.map((screen, idx) => (
              <button
                key={screen.id}
                onClick={() => setActiveScreen(idx)}
                className={`flex items-center gap-2 px-3.5 py-2 rounded-xl text-xs font-semibold transition-all duration-200 ${
                  activeScreen === idx
                    ? "bg-gradient-to-r from-violet-600 to-cyan-600 text-white shadow-lg shadow-violet-500/30 scale-102"
                    : "text-zinc-400 hover:text-white hover:bg-white/5"
                }`}
              >
                {screen.id === "radar" && <MapPin className="w-3.5 h-3.5" />}
                {screen.id === "festival" && <Share2 className="w-3.5 h-3.5" />}
                {screen.id === "reviews" && <Star className="w-3.5 h-3.5" />}
                {screen.id === "dashboard" && <TrendingUp className="w-3.5 h-3.5" />}
                <span>{screen.label}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Orbiting Glass Badges (Floating on Desktop) */}
        {/* Orbit 1: Google Maps Rank (Top Left) */}
        <div className="hidden lg:flex absolute top-16 -left-12 z-20 items-center gap-3 p-3.5 rounded-2xl bg-[#090918]/90 border border-emerald-500/40 backdrop-blur-xl shadow-2xl shadow-emerald-950/40">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
            <MapPin className="w-5 h-5" />
          </div>
          <div>
            <div className="text-[10px] text-zinc-400 uppercase font-mono">Google Maps 3-Pack</div>
            <div className="text-sm font-black text-white flex items-center gap-1.5">
              Rank #1 Locally 🥇 <span className="text-[11px] text-emerald-400 font-mono">+184% calls</span>
            </div>
          </div>
        </div>

        {/* Orbit 2: 5-Star WhatsApp Review (Top Right) */}
        <div className="hidden lg:flex absolute top-24 -right-12 z-20 items-center gap-3 p-3.5 rounded-2xl bg-[#090918]/90 border border-amber-500/40 backdrop-blur-xl shadow-2xl shadow-amber-950/40">
          <div className="w-10 h-10 rounded-xl bg-amber-500/20 border border-amber-500/30 flex items-center justify-center text-amber-400">
            <Star className="w-5 h-5 fill-amber-400" />
          </div>
          <div>
            <div className="text-[10px] text-zinc-400 uppercase font-mono">WhatsApp Review Booster</div>
            <div className="text-sm font-black text-white flex items-center gap-1">
              5.0 ★ Rating Logged <span className="text-xs text-amber-400 font-mono">(480+ Reviews)</span>
            </div>
          </div>
        </div>

        {/* Orbit 3: Daily Festival Creatives (Bottom Left) */}
        <div className="hidden lg:flex absolute bottom-20 -left-14 z-20 items-center gap-3 p-3.5 rounded-2xl bg-[#090918]/90 border border-pink-500/40 backdrop-blur-xl shadow-2xl shadow-pink-950/40">
          <div className="w-10 h-10 rounded-xl bg-pink-500/20 border border-pink-500/30 flex items-center justify-center text-pink-400">
            <Share2 className="w-5 h-5" />
          </div>
          <div>
            <div className="text-[10px] text-zinc-400 uppercase font-mono">Daily Festival Studio</div>
            <div className="text-sm font-black text-white">
              Diwali Banner Auto-Branded ✨
            </div>
          </div>
        </div>

        {/* Orbit 4: Real Local Walk-ins (Bottom Right) */}
        <div className="hidden lg:flex absolute bottom-12 -right-14 z-20 items-center gap-3 p-3.5 rounded-2xl bg-[#090918]/90 border border-cyan-500/40 backdrop-blur-xl shadow-2xl shadow-cyan-950/40">
          <div className="w-10 h-10 rounded-xl bg-cyan-500/20 border border-cyan-500/30 flex items-center justify-center text-cyan-400">
            <TrendingUp className="w-5 h-5" />
          </div>
          <div>
            <div className="text-[10px] text-zinc-400 uppercase font-mono">Footfall Engine</div>
            <div className="text-sm font-black text-white">
              +148% Local Customer Walk-ins 🚀
            </div>
          </div>
        </div>

        {/* Centered Realistic 3D iPhone 16 Pro Frame */}
        <div className="flex justify-center">
          <ThreeDCard depth={30} glowColor="rgba(124, 58, 237, 0.45)">
            <div className="relative w-[300px] sm:w-[340px] md:w-[380px] rounded-[52px] p-3.5 bg-gradient-to-b from-zinc-700 via-zinc-800 to-zinc-950 shadow-[0_30px_90px_rgba(0,0,0,0.9),0_0_50px_rgba(124,58,237,0.25)] border border-white/20">
              <BorderBeam size={280} duration={9} colorFrom="#7c3aed" colorTo="#06b6d4" />

              {/* iPhone Metallic Rim & Outer Bezel */}
              <div className="relative rounded-[44px] overflow-hidden bg-black p-2 border border-white/10 shadow-inner">
                {/* iPhone Inner Screen Container */}
                <div className="relative rounded-[36px] overflow-hidden bg-zinc-950 aspect-[9/19.5]">
                  {/* Dynamic Island Header */}
                  <div className="absolute top-0 inset-x-0 h-11 z-30 flex items-center justify-between px-6 pt-2">
                    <span className="text-[11px] font-bold text-white font-mono">9:41</span>
                    {/* Dynamic Island Pill */}
                    <div className="w-24 h-6 rounded-full bg-black border border-white/10 flex items-center justify-between px-2.5">
                      <div className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                      <div className="w-2.5 h-2.5 rounded-full bg-zinc-900 border border-zinc-700" />
                    </div>
                    <div className="flex items-center gap-1.5 text-white">
                      <Wifi className="w-3 h-3 text-white" />
                      <Battery className="w-3.5 h-3.5 text-white" />
                    </div>
                  </div>

                  {/* Active Screen Visual */}
                  <div className="relative w-full h-full">
                    <Image
                      src={current.image}
                      alt={current.alt}
                      fill
                      priority
                      className="object-cover transition-all duration-500"
                      sizes="(max-width: 768px) 340px, 380px"
                    />

                    {/* Gradient Overlay & In-App Dynamic Telemetry Card */}
                    <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-transparent to-black/30 pointer-events-none" />

                    {/* Bottom In-App Floating Pill */}
                    <div className="absolute bottom-5 inset-x-4 p-3 rounded-2xl bg-black/80 border border-white/15 backdrop-blur-md text-left shadow-2xl">
                      <div className="flex items-center justify-between mb-1">
                        <span className={`text-[10px] font-mono px-2 py-0.5 rounded-full border ${current.badgeColor}`}>
                          {current.label}
                        </span>
                        <span className="flex h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse" />
                      </div>
                      <div className="text-xs font-bold text-white">{current.title}</div>
                      <div className="text-[11px] text-zinc-400 truncate">{current.subtitle}</div>
                    </div>
                  </div>

                  {/* iPhone Home Indicator Bar */}
                  <div className="absolute bottom-1.5 inset-x-0 flex justify-center z-30">
                    <div className="w-32 h-1 rounded-full bg-white/40" />
                  </div>
                </div>
              </div>
            </div>
          </ThreeDCard>
        </div>
      </div>
    </section>
  );
}
