"use client";

import React, { useState } from "react";
import Image from "next/image";
import { Sparkles, ChevronLeft, ChevronRight } from "lucide-react";
import { RevealOnScroll } from "@/components/ui/ParallaxSection";

const appScreenshots = [
  {
    badge: "Auto Review Replies",
    title: "AI-Powered Auto Replies on Reviews",
    desc: "Every Google review receives an instant, contextual, and polite reply generated by AI. Never leave customers waiting while you manage your busy shop.",
    metric: "16 Pending Reviews Cleared in Seconds",
    url: "/images/app-screen-0.png",
  },
  {
    badge: "Google Audit Score",
    title: "Detailed Google Business Report Analysis",
    desc: "Instant health audit analyzing your Google Maps listing completeness, verification status, active posting days, and missed ranking factors.",
    metric: "0–100 Actionable Profile Health Score",
    url: "/images/app-screen-1.png",
  },
  {
    badge: "Competitor Intelligence",
    title: "Know Your Competitors & Market Share",
    desc: "Deep-dive into nearby competitor ratings, total review counts, and operational strengths & weaknesses to outrank them in local 3-pack searches.",
    metric: "Real-time Competitor Benchmarking",
    url: "/images/app-screen-2.png",
  },
  {
    badge: "Keyword Ranking",
    title: "Rank Higher with Top Local Keywords",
    desc: "Identify the exact search keywords nearby customers type into Google (e.g. 'best restaurant near me', 'open now') and optimize your profile.",
    metric: "Top Search Keyword Radar Across Your Pin Radius",
    url: "/images/app-screen-3.png",
  },
  {
    badge: "WhatsApp Integration",
    title: "Daily Performance Reports on WhatsApp",
    desc: "Get morning business summaries, review alerts, and 1-tap AI approval prompts sent directly to your WhatsApp without opening complex software.",
    metric: "Zero Dashboard Fatigue • 100% WhatsApp Native",
    url: "/images/app-screen-4.png",
  },
];

export function AppScreenshotsShowcase() {
  const [activeScreenIndex, setActiveScreenIndex] = useState(0);

  const nextScreen = () => {
    setActiveScreenIndex((prev) => (prev + 1) % appScreenshots.length);
  };

  const prevScreen = () => {
    setActiveScreenIndex((prev) => (prev - 1 + appScreenshots.length) % appScreenshots.length);
  };

  return (
    <section className="py-14 sm:py-24 px-4 container mx-auto max-w-7xl relative border-t border-white/10 bg-[#060618]/60 overflow-hidden">
      <RevealOnScroll direction="up" delay={0.1}>
        <div className="text-center max-w-3xl mx-auto mb-8 md:mb-16 space-y-4">
          <span className="text-xs font-bold text-purple-400 uppercase tracking-widest bg-purple-500/10 px-3.5 py-1.5 rounded-full border border-purple-500/20">
            Native Mobile Experience
          </span>
          <h2 className="font-heading text-3xl md:text-5xl font-extrabold text-white tracking-tight">
            Built for Busy Business Owners
          </h2>
          <p className="text-base md:text-lg text-slate-300">
            A clean, intuitive mobile app designed for busy entrepreneurs who need real customer results, not complexity.
          </p>
        </div>
      </RevealOnScroll>

      {/* Carousel / Interactive Mobile Showcase */}
      <div className="max-w-6xl mx-auto grid lg:grid-cols-12 gap-8 lg:gap-12 items-center">
        {/* Active Screen Display in High-Fidelity Showcase Frame */}
        <div className="lg:col-span-6 flex flex-col items-center justify-center">
          <RevealOnScroll delay={0.05}>
            <div className="w-full max-w-[480px] rounded-3xl p-3 sm:p-4 bg-gradient-to-b from-white/[0.09] via-white/[0.04] to-transparent border border-white/15 shadow-[0_25px_60px_rgba(0,0,0,0.85)] backdrop-blur-xl">
              {/* Showcase Top Bar */}
              <div className="flex items-center justify-between pb-3 px-1 border-b border-white/10 mb-3">
                <div className="flex items-center gap-1.5">
                  <div className="w-2.5 h-2.5 rounded-full bg-red-500/70" />
                  <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/70" />
                  <div className="w-2.5 h-2.5 rounded-full bg-emerald-500/70" />
                </div>
                <div className="text-[11px] font-mono font-medium text-zinc-400 bg-white/5 px-3 py-0.5 rounded-full border border-white/10">
                  dhandhagrow.com • {appScreenshots[activeScreenIndex].badge}
                </div>
                <div className="flex items-center gap-1.5 text-[10px] font-medium text-emerald-400">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                  Live Sync
                </div>
              </div>

              {/* Exact 1:1 Aspect Canvas with Zero-Crop Containment */}
              <div className="relative w-full aspect-square rounded-2xl overflow-hidden bg-[#070716] border border-white/10 shadow-inner flex items-center justify-center p-2">
                <Image
                  src={appScreenshots[activeScreenIndex].url}
                  alt={appScreenshots[activeScreenIndex].title}
                  fill
                  sizes="(max-width: 768px) 100vw, 480px"
                  className="object-contain transition-all duration-300 rounded-xl"
                  loading="lazy"
                />
              </div>

              {/* Quick Thumbnails Row */}
              <div className="grid grid-cols-5 gap-1.5 pt-3 mt-1">
                {appScreenshots.map((item, idx) => (
                  <button
                    key={idx}
                    onClick={() => setActiveScreenIndex(idx)}
                    className={`relative aspect-square rounded-lg overflow-hidden border transition-all ${
                      activeScreenIndex === idx
                        ? "border-purple-400 ring-2 ring-purple-500/50 scale-105 shadow-md shadow-purple-600/30"
                        : "border-white/10 opacity-60 hover:opacity-100 hover:border-white/30"
                    }`}
                    aria-label={`View screenshot ${idx + 1}: ${item.badge}`}
                  >
                    <Image
                      src={item.url}
                      alt={item.title}
                      fill
                      sizes="80px"
                      className="object-cover"
                      loading="lazy"
                    />
                  </button>
                ))}
              </div>
            </div>
          </RevealOnScroll>
        </div>

        {/* Navigation & Screen Details */}
        <div className="lg:col-span-6">
          <RevealOnScroll delay={0.05}>
            <div className="space-y-6">
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <span className="text-xs font-bold text-cyan-400 uppercase tracking-wider bg-cyan-500/10 px-3 py-1 rounded-full border border-cyan-500/20">
                    Screen {activeScreenIndex + 1} of {appScreenshots.length}
                  </span>
                  <span className="text-xs font-medium text-zinc-400 bg-white/5 px-2.5 py-1 rounded-full border border-white/5">
                    {appScreenshots[activeScreenIndex].badge}
                  </span>
                </div>
                <h3 className="font-heading text-2xl sm:text-3xl font-bold text-white tracking-tight">
                  {appScreenshots[activeScreenIndex].title}
                </h3>
                <p className="text-slate-300 text-sm sm:text-base leading-relaxed">
                  {appScreenshots[activeScreenIndex].desc}
                </p>
                
                {/* Highlight Metric Pill */}
                <div className="inline-flex items-center gap-2 px-3.5 py-2 rounded-xl bg-purple-500/10 border border-purple-500/20 text-purple-300 text-xs sm:text-sm font-semibold">
                  <Sparkles className="w-4 h-4 text-purple-400 shrink-0" />
                  <span>{appScreenshots[activeScreenIndex].metric}</span>
                </div>
              </div>

              {/* Selector list */}
              <div className="space-y-2 pt-1">
                {appScreenshots.map((screen, idx) => (
                  <button
                    key={idx}
                    onClick={() => setActiveScreenIndex(idx)}
                    className={`w-full text-left p-3.5 rounded-xl text-xs sm:text-sm font-semibold transition-all flex items-center justify-between border ${
                      activeScreenIndex === idx
                        ? "bg-gradient-to-r from-purple-950/60 to-purple-900/40 border-purple-500/60 text-white shadow-lg shadow-purple-950/40"
                        : "bg-white/[0.03] hover:bg-white/[0.07] border-white/5 text-slate-400 hover:text-white"
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <span className={`w-6 h-6 rounded-lg text-xs flex items-center justify-center font-bold ${
                        activeScreenIndex === idx ? "bg-purple-500 text-white" : "bg-white/5 text-zinc-400"
                      }`}>
                        0{idx + 1}
                      </span>
                      <span>{screen.title}</span>
                    </div>
                    {activeScreenIndex === idx && <ChevronRight className="w-4 h-4 text-cyan-300 shrink-0" />}
                  </button>
                ))}
              </div>

              {/* Carousel Arrow Controls */}
              <div className="flex items-center justify-between pt-2">
                <div className="flex gap-2">
                  {appScreenshots.map((_, idx) => (
                    <button
                      key={idx}
                      onClick={() => setActiveScreenIndex(idx)}
                      className={`h-2 rounded-full transition-all ${
                        activeScreenIndex === idx ? "w-8 bg-purple-500" : "w-2 bg-white/20 hover:bg-white/40"
                      }`}
                      aria-label={`Jump to screenshot ${idx + 1}`}
                    />
                  ))}
                </div>
                <div className="flex gap-3">
                  <button
                    onClick={prevScreen}
                    aria-label="Previous screenshot"
                    className="w-10 h-10 rounded-full bg-white/5 hover:bg-white/10 border border-white/10 flex items-center justify-center text-white transition-colors"
                  >
                    <ChevronLeft className="w-5 h-5" />
                  </button>
                  <button
                    onClick={nextScreen}
                    aria-label="Next screenshot"
                    className="w-10 h-10 rounded-full bg-white/5 hover:bg-white/10 border border-white/10 flex items-center justify-center text-white transition-colors"
                  >
                    <ChevronRight className="w-5 h-5" />
                  </button>
                </div>
              </div>
            </div>
          </RevealOnScroll>
        </div>
      </div>
    </section>
  );
}
